### ISSUE TITLE
ProtectedConfigurationBuilder value contains escaped (doubled up) backslashes

### ISSUE THREAD

**Issue by Cynicszm** [fededim/Fededim.Extensions.Configuration.Protected#17]
Hi,

Thanks for the work. 

Was creating a test project to encrypt JSON files using Nuget version 1.0.5 and noticed that double backslashes in the unencrypted value (\\\\) are encrypted successfully but are returned as escaped backslashes when accessed in the ProtectedConfigurationBuilder (\\\\\\\\)

This is especially important when using connection strings and trying to store a Server\\\\Instance value

e.g. 
Unencrypted in appSettings.json
`{
  "ConnectionStrings": {
    "DatabaseConnectionString": "Protect:{Server=(LocalDb)\\MSSQLLocalDB;}"
  }`

The decrypted value In code from the ProtectedConfigurationBuilder is Server=(LocalDb)\\\\\\\\MSSQLLocalDB; and I would expect it to be Server=(LocalDb)\\\\MSSQLLocalDB;

**Comment by Cynicszm** [comment]
Turns out this behaviour is in the DataProtect Protect / Unprotect. Closing

**Comment by fededim** [comment]
Hi,

sorry for the late reply, but I was busy, you were right there was a bug, the backslash was double escaped, **not due to DataProtect Protect /  Unprotect but instead due to Regex which escapes some special characters (among which there is the obvious backslash, see [Regex.Escape](https://learn.microsoft.com/it-it/dotnet/api/system.text.regularexpressions.regex.escape?view=net-8.0) function) when extracting groups value**. To solve this I had just to use [Regex.Unescape](https://learn.microsoft.com/it-it/dotnet/api/system.text.regularexpressions.regex.unescape?view=net-8.0#system-text-regularexpressions-regex-unescape(system-string)) function before encrypting any value extracted from the regex, I am releasing package version 1.0.6 shortly with the fix (see the screenshot below).

Thank you very much for using and testing my package and for having raised a bug which I didn't notice.

![image](https://github.com/fededim/Fededim.Extensions.Configuration.Protected/assets/8364158/a266e17f-f3ee-4b7e-a7a3-7ec0d6e438cc)

**Comment by Cynicszm** [comment]
Thanks for the update. I’ll keep an eye out for the 1.0.6 version.

**Comment by fededim** [comment]
Give me some more time, while testing now I understood the real problem, it is the encryption of json and xml files....basically I read both of them just by using File.ReadAllText which gets the raw characters without decoding the format of the particular file (in JSON \ must be double escaped, in XML \&lt\; must be replaced by <) so to read these files I can't simply use File.ReadAllText

**Comment by fededim** [comment]
I have just published the [new version 1.0.6](https://www.nuget.org/packages/Fededim.Extensions.Configuration.Protected/1.0.6) of the package, the bug should be fixed now as the ProtectFiles method should decode all input files according to their format (JSON and XML are supported for now, but I added also an extension point in order to allow anyone to support any other format they need, see ConfigurationBuilderExtensions.FilesDecoding public property). **By the way you have to re-encrypt the json/xml files in your project otherwise it won't work.**

Test it when you have time and let me know if everything is fine.

**Comment by Cynicszm** [comment]
Looks like that fixed it. I tested using an appsettings ConnectionString and it work fine. 

Thanks for the quick response
